# chart-repo: argo/argo-cd

##
# kubectl create namespace devops
# kubectl apply -n devops -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

nameOverride: argocd

installCRDs: true

controller:
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-operator
  podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

server:
  extraArgs:
    - --insecure

  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      additionalLabels:
        release: prometheus-operator
  podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

  ingress:
    enabled: true
    annotations:
      # cert-manager.io/cluster-issuer: "letsencrypt-issuer"
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
    hosts:
      - "argocd.tools.k8s.jwdevtools.cf"
    # tls:
    #   - secretName: argocd-server-tls
    #     hosts:
    #       - "argocd.scdf.k8s.jwdevtools.cf"

  config:
    url: "https://argocd.tools.k8s.jwdevtools.cf"

    repositories: |
      - name: stable
        type: helm
        url: https://kubernetes-charts.storage.googleapis.com
      - name: argo
        type: helm
        url: https://argoproj.github.io/argo-helm

    kustomize.buildOptions: --load_restrictor none


  # https://argoproj.github.io/argo-cd/operator-manual/user-management/keycloak/

  rbacConfig:
    policy.default: role:readonly
    policy.csv: |
      g, "/admin", role:admin

